apps:
  # Personal Apps
  cura:
    forPersonal: true
    windows:
      id: "Ultimaker.Cura"
      folder: "Cura"
      method: "winget"
  steam:
    forPersonal: true
    windows:
      id: "Valve.Steam"
      folder: "Steam"
      method: "winget"
  rainmeter:
    forPersonal: true
    windows:
      id: "Rainmeter.Rainmeter"
      folder: "Rainmeter"
      method: "winget"
  # CLI Tools
  terraform:
    forPersonal: false
    windows:
      id: "terraform"
      method: "choco"
  velero:
    forPersonal: false
    windows:
      id: "velero"
      method: "choco"
  bitwarden-cli:
    forPersonal: false
    windows:
      id: "bitwarden-cli"
      method: "choco"
  flux:
    forPersonal: false
    windows:
      id: "flux"
      method: "choco"
  go-task:
    forPersonal: false
    windows:
      id: "go-task"
      method: "choco"
  pyenv-win:
    forPersonal: false
    windows:
      id: "pyenv-win"
      method: "choco"
  github-cli:
    forPersonal: false
    windows:
      id: "GitHub.cli"
      folder: "Github-CLI"
      method: "winget"
  clink:
    forPersonal: false
    windows:
      id: "chrisant996.Clink"
      folder: "Clink"
      method: "winget"
  git:
    forPersonal: false
    windows:
      id: "Git.Git"
      folder: "Git"
      method: "winget"
  kubectl:
    forPersonal: false
    windows:
      id: "Kubernetes.kubectl"
      folder: "Kubectl"
      method: "winget"
  nvm:
    forPersonal: false
    windows:
      id: "CoreyButler.NVMforWindows"
      folder: "NVM"
      method: "winget"
  starship:
    forPersonal: false
    windows:
      id: "Starship.Starship"
      folder: "Starship"
      method: "winget"
  # Browser
  firefox-dev:
    forPersonal: false
    windows:
      id: "Mozilla.Firefox.DeveloperEdition"
      folder: "Firefox-Dev"
      method: "winget"
  chrome:
    forPersonal: false
    windows:
      id: "Google.Chrome"
      folder: "Chrome"
      method: "winget"
  # Media
  icloud:
    forPersonal: false
    windows:
      id: "icloud"
      method: "choco"
  # Developer Tools
  vscode:
    forPersonal: false
    windows:
      id: "Microsoft.VisualStudioCode.Insiders"
      folder: "VSCode"
      method: "winget"
  postman:
    forPersonal: false
    windows:
      id: "Postman.Postman"
      folder: "Postman"
      method: "winget"
  yubikey-manager:
    forPersonal: false
    windows:
      id: "Yubico-YubikeyManager"
      folder: "Yubikey"
      method: "winget"
  putty:
    forPersonal: false
    windows:
      id: "PuTTY.PuTTY"
      folder: "Putty"
      method: "winget"