- name: "{{ item.name }} : Substitute environment variables in destination"
  set_fact:
    env: "{{ item.destination | regex_search('\\$(\\w+)', '\\1') | first }}"
  when: item.destination | regex_search('\\$(\\w+)')
- name: "{{ item.name }} : Symlink file"
  ansible.builtin.file:
    src: "{{ PWD }}/dotfiles/{{ item.src | default('') }}/{{ item.name }}"
    dest: "{{ destination }}/{{ item.name }}"
    force: yes
  vars:
    destination: "{{ item.destination | regex_replace('\\$\\w+', lookup('env', env)) | default(item.destination) }}"