---
- name: Install Brew Apps
  community.general.homebrew:
    name: "{{ item }}"
  vars:
    jmesquery: "[?method=='brew'].items"
  with_items: "{{ apps | community.general.json_query(jmesquery) | list }}"
- name: Install Brew Cask Apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  vars:
    jmesquery: "[?method=='brew-cask'].items"
  with_items: "{{ apps | community.general.json_query(jmesquery) | list }}"
- name: Add Apt Repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  vars:
    jmesquery: "[?method=='apt-repository'].items"
  with_items: "{{ apps | community.general.json_query(jmesquery) | list }}" 
- name: Install Apt Packages
  apt:
    name: "{{ item }}"
  vars:
    jmesquery: "[?method=='apt'].items"
  with_items: "{{ apps | community.general.json_query(jmesquery) | list }}"  
- name: Install Script Apps
  ansible.builtin.script: "{{ PWD }}/scripts/{{ item }}.sh"
  register: script_install
  vars:
    jmesquery: "[?method=='script'].items"
  with_items: "{{ apps | community.general.json_query(jmesquery) | list }}"
- name: Install Chocolately Apps
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
  vars:
    jmesquery: "[?method=='chocolately'].items"
  with_items: "{{ apps | community.general.json_query(jmesquery) | list }}"